# Generated by Django 4.2.30 on 2026-04-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='ID пользователя')),
                ('question', models.TextField(verbose_name='Сообщение')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ поддержки')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Отвечено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
