# Generated by Django 4.2.30 on 2026-04-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquery',
            options={'verbose_name': 'Запрос пользователя', 'verbose_name_plural': 'История запросов'},
        ),
        migrations.AddField(
            model_name='userquery',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Статус ответа'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='question',
            field=models.TextField(verbose_name='Запрос пользователя'),
        ),
    ]
